In [2]:
import numpy as np

# Number of vertices
N = 6

# Edges
edges = [
    (0, 1),
    (0, 2),
    (1, 2),
    (3, 4),
    (4, 5),
    (3, 5)
]

# 1. Construct Adjacency Matrix
A = np.zeros((N, N))

for u, v in edges:
    A[u][v] = 1
    A[v][u] = 1

print("Adjacency Matrix:")
print(A.astype(int))

# 2. Construct Degree Matrix
D = np.diag(np.sum(A, axis=1))

print("\nDegree Matrix:")
print(D.astype(int))

# 3. Construct Laplacian Matrix
L = D - A

print("\nLaplacian Matrix:")
print(L.astype(int))

# 4. Compute Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eigh(L)

print("\nEigenvalues:")
print(np.round(eigenvalues, 4))

print("\nEigenvectors:")
print(np.round(eigenvectors, 4))

# 5. Use the second smallest eigenvector
fiedler_vector = eigenvectors[:, 1]

print("\nFiedler Vector:")
print(np.round(fiedler_vector, 4))

# Partition using the sign of the Fiedler vector
cluster1 = []
cluster2 = []

for i in range(N):
    if fiedler_vector[i] < 0:
        cluster1.append(i)
    else:
        cluster2.append(i)

print("\nClusters:")
print("Cluster 1:", cluster1)
print("Cluster 2:", cluster2)

Adjacency Matrix:
[[0 1 1 0 0 0]
 [1 0 1 0 0 0]
 [1 1 0 0 0 0]
 [0 0 0 0 1 1]
 [0 0 0 1 0 1]
 [0 0 0 1 1 0]]

Degree Matrix:
[[2 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 2 0]
 [0 0 0 0 0 2]]

Laplacian Matrix:
[[ 2 -1 -1  0  0  0]
 [-1  2 -1  0  0  0]
 [-1 -1  2  0  0  0]
 [ 0  0  0  2 -1 -1]
 [ 0  0  0 -1  2 -1]
 [ 0  0  0 -1 -1  2]]

Eigenvalues:
[0. 0. 3. 3. 3. 3.]

Eigenvectors:
[[ 0.5774  0.     -0.6395  0.     -0.     -0.5077]
 [ 0.5774  0.     -0.1199  0.     -0.      0.8076]
 [ 0.5774  0.      0.7594  0.     -0.     -0.3   ]
 [ 0.      0.5774  0.     -0.8059  0.131  -0.    ]
 [ 0.      0.5774  0.      0.5164  0.6325 -0.    ]
 [ 0.      0.5774  0.      0.2895 -0.7634 -0.    ]]

Fiedler Vector:
[0.     0.     0.     0.5774 0.5774 0.5774]

Clusters:
Cluster 1: []
Cluster 2: [0, 1, 2, 3, 4, 5]
